### ISSUE TITLE
no support for names such as *.x.domain.com (tested with OVH scripts)

### ISSUE THREAD

**Issue by sebguilbaud** [sblaisot/certbot-dns-01-authenticators#2]
OVH scripts do not work with "complicated" names such as *.x.domain.com, I have a workaround using get_tld to extract "real" domain name, are you interested ?

**Comment by shoten** [comment]
Hi @sebguilbaud !
I have the same issue as you, I'm interested in your workaround :)
I have to auto renew a *.sub.domain.com but for the moment I'm stuck in the depth of ovh.
I would gladly accept some help if you still have your script.
Thanks in advance !

**Comment by sebguilbaud** [comment]
I no longer use certbot to manage my LE certificates, it was way too cumbersome on older machines. 
Take a look at acmemgr.sh (https://github.com/sowebio/acmemgr.sh), is works wonderfully even if the initial setup is more complex
